export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";
export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const INCREASE_INGREDIENTS_COUNTER = "INCREASE_INGREDIENTS_COUNTER";
export const DECREASE_INGREDIENTS_COUNTER = "DECREASE_INGREDIENTS_COUNTER";

export type IngredientsListActionType =
    | typeof GET_INGREDIENTS_SUCCESS
    | typeof GET_INGREDIENTS_ERROR
    | typeof GET_INGREDIENTS_REQUEST
    | typeof INCREASE_INGREDIENTS_COUNTER
    | typeof DECREASE_INGREDIENTS_COUNTER;
