export const USER_REQUEST = "USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_WITH_CODE_FAILED = "PASSWORD_RESET_WITH_CODE_FAILED";
export const PASSWORD_RESET_WITH_CODE_SUCCESS = "PASSWORD_RESET_WITH_CODE_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";


export type UserActionType =
    | typeof USER_REQUEST
    | typeof REGISTER_USER_SUCCESS
    | typeof REGISTER_USER_ERROR
    | typeof PASSWORD_RESET_FAILED
    | typeof LOGIN_USER_SUCCESS
    | typeof LOGIN_USER_ERROR
    | typeof USER_PROFILE_ERROR
    | typeof USER_PROFILE_SUCCESS
    | typeof REFRESH_TOKEN_SUCCESS
    | typeof REFRESH_TOKEN_FAILED
    | typeof PASSWORD_RESET_SUCCESS
    | typeof PASSWORD_RESET_WITH_CODE_FAILED
    | typeof PASSWORD_RESET_WITH_CODE_SUCCESS
    | typeof LOGOUT_USER_FAILED
    | typeof LOGOUT_USER_SUCCESS
    | typeof UPDATE_PROFILE_FAILED
    | typeof PASSWORD_RESET_WITH_CODE_SUCCESS
    | typeof UPDATE_PROFILE_SUCCESS;

